# Permalinks
permalink:           /:categories/:title/

# Setup
title:               Owen Jow
tagline:             Just your everyday writer
url:                 http://owenjow.xyz
paginate:            15
paginate_path:       "/blog/:num"
baseurl:             ""

# Assets
sass:
  sass_dir:          sass
  style:             :compressed

# About / contact
author:
  name:              Owen Jow
  url:               http://owenjow.xyz
  email:             owenjow@berkeley.edu

# Gems
gems:                [jekyll-paginate]

# Collections
collections:
  articles:
    output:          true
